[versions]
jdk = "21"
gradle = "8.13"
agp = "8.13.2"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
compose-bom = "2025.10.01"
adaptive = "1.2.0"
activity = "1.11.0"
lifecycle = "2.9.4"
navigation = "2.9.5"
serialization = "1.9.0"
coroutines = "1.10.2"
room = "2.8.5"
sqlite = "2.7.1"
junit = "4.13.2"
test-runner = "1.7.0"
test-junit = "1.3.0"
test-core = "1.7.0"
espresso = "3.7.0"
bcrypt = "0.10.2"

[libraries]
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
junit = { module = "junit:junit", version.ref = "junit" }
test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }
test-core = { module = "androidx.test:core-ktx", version.ref = "test-core" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
