import { movementKey, statusKey } from '../../../utils/entityLabels';
import { Ban, Check, Eye, PackagePlus, Plus, Truck } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Button, ConfirmDialog, EmptyState, Modal, NumberInput, Select, Tabs, TextInput } from '../../../design-system';
import { useStorePreferences } from '../../../hooks/useStorePreferences';
import { operationsService } from '../../../services/operationsService';
import { productService } from '../../../services/productService';
import type { Product } from '../../../types';
import { ProductList } from '../products/ProductList';
import { authService } from '../../../services/authService';
import { can, type EffectivePermission } from '../../../security/permissions';
import { formatMoney } from '../../../utils/formatters';

type Supplier = { id: number; name: string; phone?: string; email?: string; address?: string };
type PurchaseDraft = { id: number; reference: string; status: string; items: Array<{ product: Product; quantity: number; unitCost: number }> };

export function PurchasesPage({ userId, notify }: { userId: number; notify: (message: string) => void }) {
  const { t } = useTranslation();
  const { currency } = useStorePreferences();
  const [creatingArticle, setCreatingArticle] = useState(false);
  const [articleId, setArticleId] = useState('');
  const [lineQuantity, setLineQuantity] = useState('');
  const [lineCost, setLineCost] = useState('');
  const [permissions, setPermissions] = useState<EffectivePermission[]>([]);
  useEffect(() => { void authService.session().then((view) => setPermissions(view.effectivePermissions)).catch(() => notify(t('operationFailed'))); }, []);
  const [tab, setTab] = useState('purchases');
  const [purchases, setPurchases] = useState<any[]>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [purchaseForm, setPurchaseForm] = useState({ supplierId: '', supplierInvoice: '', note: '' });
  const [supplierEdit, setSupplierEdit] = useState<Partial<Supplier> | null>(null);
  const [draft, setDraft] = useState<PurchaseDraft | null>(null);
  const [validateConfirm, setValidateConfirm] = useState(false);
  const [cancelTarget, setCancelTarget] = useState<any>(null);
  const [cancelReason, setCancelReason] = useState('');
  const [detail, setDetail] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const actionLock = useRef(false);
  const purchaseKey = useRef<string | null>(null);
  const load = async () => {
    const [purchaseRows, supplierRows, productRows] = await Promise.all([operationsService.purchases({}), operationsService.suppliers(), productService.list({})]);
    setPurchases(purchaseRows); setSuppliers(supplierRows); setProducts(productRows);
  };
  useEffect(() => { void load(); }, []);
  const filteredPurchases = useMemo(() => purchases.filter((purchase) => (!status || purchase.status === status) && [purchase.reference, purchase.supplier, purchase.supplier_invoice].filter(Boolean).join(' ').toLowerCase().includes(search.trim().toLowerCase())), [purchases, search, status]);
  const filteredSuppliers = suppliers.filter((supplier) => [supplier.name, supplier.email, supplier.phone].filter(Boolean).join(' ').toLowerCase().includes(search.trim().toLowerCase()));
  const draftTotal = draft?.items.reduce((sum, item) => sum + item.quantity * item.unitCost, 0) ?? 0;

  const createPurchase = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (actionLock.current) return; actionLock.current = true; setBusy(true);
    const form = new FormData(event.currentTarget); purchaseKey.current ||= crypto.randomUUID();
    try { const created = await operationsService.createPurchase({ supplierId: Number(form.get('supplierId')) || undefined, supplierInvoice: String(form.get('supplierInvoice') || ''), note: String(form.get('note') || ''), idempotencyKey: purchaseKey.current, userId }); setArticleId(''); setLineQuantity(''); setLineCost(''); setDraft({ ...created, items: [] }); purchaseKey.current = null; setCreateOpen(false); await load(); }
    catch { notify(t('operationFailed')); }
    finally { actionLock.current = false; setBusy(false); }
  };
  const saveSupplier = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (actionLock.current) return; actionLock.current = true; setBusy(true);
    const form = Object.fromEntries(new FormData(event.currentTarget));
    try { const id = await operationsService.saveSupplier({ ...supplierEdit, ...form, userId }); if (createOpen) setPurchaseForm((current) => ({ ...current, supplierId: String(id) })); setSupplierEdit(null); await load(); notify(t('supplierSaved')); }
    catch { notify(t('operationFailed')); }
    finally { actionLock.current = false; setBusy(false); }
  };
  const purchasePanel = <div className="ops-domain"><div className="ops-page__subactions"><Button icon={Plus} onClick={() => { setPurchaseForm({ supplierId: '', supplierInvoice: '', note: '' }); setCreateOpen(true); }}>{t('newPurchase')}</Button></div><div className="ops-filters"><TextInput type="search" label={t('searchPurchases')} value={search} onChange={(event) => setSearch(event.target.value)} /><Select label={t('status')} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t('allStatuses')}</option><option value="DRAFT">{t('draft')}</option><option value="VALIDATED">{t('validated')}</option><option value="CANCELLED">{t('cancelled')}</option></Select></div>{!filteredPurchases.length ? <EmptyState title={t('noPurchases')} description={t('noPurchasesHint')} /> : <div className="ops-list">{filteredPurchases.map((purchase) => { const normalized = String(purchase.status).toLowerCase(); return <article className="ops-list-item" key={purchase.id}><div className="ops-list-item__main"><strong>{purchase.reference}</strong><span>{purchase.supplier || t('noSupplier')} · {new Date(purchase.created_at).toLocaleString()}</span></div><strong>{formatMoney(Number(purchase.total_amount || 0), currency)}</strong><span className={`ops-status ops-status--${normalized}`}>{t(statusKey(purchase.status))}</span><Button size="sm" variant="secondary" icon={Eye} onClick={() => void operationsService.purchaseDetail(purchase.id).then(setDetail).catch(() => notify(t('operationFailed')))}>{t('details')}</Button><Button size="sm" variant="secondary" icon={Ban} disabled={normalized === 'cancelled'} onClick={() => setCancelTarget(purchase)}>{t('cancel')}</Button></article>; })}</div>}</div>;
  const supplierPanel = <div className="ops-domain"><div className="ops-page__subactions"><Button icon={Plus} onClick={() => setSupplierEdit({})}>{t('newSupplier')}</Button></div><TextInput type="search" label={t('searchSuppliers')} value={search} onChange={(event) => setSearch(event.target.value)} />{!filteredSuppliers.length ? <EmptyState title={t('noSuppliers')} description={t('noSuppliersHint')} /> : <div className="ops-list">{filteredSuppliers.map((supplier) => <article className="ops-list-item supplier-row" key={supplier.id}><strong>{supplier.name}</strong><span aria-label={t('phone')}>{supplier.phone || '—'}</span><span aria-label={t('email')}>{supplier.email || '—'}</span><span aria-label={t('address')}>{supplier.address || '—'}</span><Button size="sm" variant="secondary" onClick={() => setSupplierEdit(supplier)}>{t('edit')}</Button></article>)}</div>}</div>;

  return <section className="ops-page" aria-labelledby="purchases-title"><header className="ops-page__header"><div><span className="eyebrow">{t('dailyOperations')}</span><h1 id="purchases-title">{t('purchases')}</h1><p>{t('purchasesPageHint')}</p></div></header><Tabs ariaLabel={t('purchaseSections')} active={tab} onChange={setTab} tabs={[{ id: 'purchases', label: <><PackagePlus size={16} /> {t('purchases')}</>, panel: purchasePanel }, { id: 'suppliers', label: <><Truck size={16} /> {t('suppliers')}</>, panel: supplierPanel }]} />
    {detail && <Modal title={detail.reference} description={t('purchaseTraceability')} closeLabel={t('close')} onClose={() => setDetail(null)}><div className="ops-domain"><dl className="ops-detail-list"><div><dt>{t('supplier')}</dt><dd>{detail.supplier || t('noSupplier')}</dd></div><div><dt>{t('status')}</dt><dd>{t(statusKey(detail.status))}</dd></div><div><dt>{t('createdBy')}</dt><dd>{detail.createdBy}</dd></div><div><dt>{t('dateAndTime')}</dt><dd>{new Date(detail.created_at).toLocaleString()}</dd></div><div><dt>{t('total')}</dt><dd>{formatMoney(Number(detail.total_amount), currency)}</dd></div></dl><h3>{t('products')}</h3>{detail.items.map((item: any) => <div className="ops-purchase-line" key={item.id}><span>{item.product}</span><span>{item.quantity} × {formatMoney(item.unit_cost, currency)}</span><strong>{formatMoney(item.total_line, currency)}</strong></div>)}<h3>{t('stockEffect')}</h3>{detail.movements.length ? detail.movements.map((movement: any) => <div className="ops-purchase-line" key={movement.id}><span>{movement.product}</span><span>{t(movementKey(movement.reason))}</span><strong>{movement.quantity > 0 ? '+' : ''}{movement.quantity}</strong></div>) : <p>{t('noStockEffect')}</p>}</div></Modal>}
    {createOpen && !supplierEdit && <Modal title={t('newPurchase')} description={t('purchaseDraftHint')} closeLabel={t('close')} onClose={() => !busy && setCreateOpen(false)} dismissible={!busy}><form className="ops-form" onSubmit={createPurchase}><Select name="supplierId" label={t('supplier')} value={purchaseForm.supplierId} onChange={(event) => { if (event.target.value === "__new") setSupplierEdit({}); else setPurchaseForm({ ...purchaseForm, supplierId: event.target.value }); }}><option value="">{t('noSupplier')}</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}{can(permissions, 'PURCHASES', 'UPDATE') && <option value="__new">{t('newSupplier')}</option>}</Select><TextInput name="supplierInvoice" label={t('supplierInvoice')} value={purchaseForm.supplierInvoice} onChange={(event) => setPurchaseForm({ ...purchaseForm, supplierInvoice: event.target.value })} /><TextInput name="note" label={t('note')} value={purchaseForm.note} onChange={(event) => setPurchaseForm({ ...purchaseForm, note: event.target.value })} /><div className="ops-form__actions"><Button type="button" variant="secondary" onClick={() => setCreateOpen(false)}>{t('cancel')}</Button><Button type="submit" loading={busy} loadingLabel={t('saving')}>{t('createDraft')}</Button></div></form></Modal>}
    {supplierEdit && <Modal title={supplierEdit.id ? t('editSupplier') : t('newSupplier')} description={t('supplierFormHint')} closeLabel={t('close')} onClose={() => !busy && setSupplierEdit(null)} dismissible={!busy}><form className="ops-form" onSubmit={saveSupplier}><TextInput name="name" label={t('name')} defaultValue={supplierEdit.name || ''} required /><TextInput name="phone" label={t('phone')} defaultValue={supplierEdit.phone || ''} /><TextInput name="email" type="email" label={t('email')} defaultValue={supplierEdit.email || ''} /><TextInput name="address" label={t('address')} defaultValue={supplierEdit.address || ''} /><div className="ops-form__actions"><Button type="button" variant="secondary" onClick={() => setSupplierEdit(null)}>{t('cancel')}</Button><Button type="submit" loading={busy} loadingLabel={t('saving')}>{t('save')}</Button></div></form></Modal>}
    {draft && !creatingArticle && <Modal title={`${t('purchaseDraft')} ${draft.reference}`} closeLabel={t('close')} onClose={() => !busy && setDraft(null)} dismissible={!busy}><div className="ops-purchase-draft"><Alert variant="warning" title={t('draft')}>{t('draftNoStockEffect')}</Alert><form className="ops-form ops-purchase-item" onSubmit={(event) => { event.preventDefault(); if (busy) return; const form = new FormData(event.currentTarget); const product = products.find((item) => item.id === Number(form.get('productId'))); if (!product) return; const quantity = Number(form.get('quantity')); const unitCost = Number(form.get('unitCost')); setBusy(true); void operationsService.savePurchaseItem({ purchaseId: draft.id, productId: product.id, quantity, unitCost }).then(() => setDraft((current) => current ? { ...current, items: [...current.items.filter((item) => item.product.id !== product.id), { product, quantity, unitCost }] } : current)).catch(() => notify(t('operationFailed'))).finally(() => setBusy(false)); }}><Select name="productId" label={t('product')} value={articleId} onChange={(event) => { if (event.target.value === "__create") setCreatingArticle(true); else setArticleId(event.target.value); }} required><option value="">{t('selectProduct')}</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}{can(permissions, 'PRODUCTS', 'UPDATE') && <option value="__create">{t('newProduct')}</option>}</Select><NumberInput name="quantity" value={lineQuantity} onChange={(event) => setLineQuantity(event.target.value)} label={t('quantity')} min="1" step="1" required /><NumberInput name="unitCost" value={lineCost} onChange={(event) => setLineCost(event.target.value)} label={`${t('unitPrice')} (${currency})`} min="0" step="0.01" required /><Button type="submit" icon={Plus} loading={busy} loadingLabel={t('saving')}>{t('addItem')}</Button></form>{draft.items.map((item) => <div className="ops-purchase-line" key={item.product.id}><span>{item.product.name}</span><span>{item.quantity} × {formatMoney(item.unitCost, currency)}</span><strong>{formatMoney(item.quantity * item.unitCost, currency)}</strong></div>)}<div className="ops-purchase-total"><span>{t('total')}</span><strong>{formatMoney(draftTotal, currency)}</strong></div><Button size="lg" icon={Check} disabled={!draft.items.length || busy} onClick={() => setValidateConfirm(true)}>{t('validatePurchase')}</Button></div></Modal>}
    {creatingArticle && <ProductList editorOnly userId={userId} permissions={permissions} notify={notify} onCancel={() => setCreatingArticle(false)} onCreated={(id) => { void load().then(() => { setArticleId(String(id)); setCreatingArticle(false); }); }} />}
    {validateConfirm && draft && <ConfirmDialog title={t('validatePurchase')} description={t('validatePurchaseConsequence')} confirmLabel={t('validate')} cancelLabel={t('cancel')} onClose={() => setValidateConfirm(false)} onConfirm={() => { if (actionLock.current) return; actionLock.current = true; setBusy(true); void operationsService.validatePurchase({ purchaseId: draft.id, userId }).then(async () => { setValidateConfirm(false); setDraft(null); await load(); notify(t('purchaseValidated')); }).catch(() => notify(t('operationFailed'))).finally(() => { actionLock.current = false; setBusy(false); }); }} />}
    {cancelTarget && <Modal title={t('cancelPurchase')} description={cancelTarget.reference} closeLabel={t('close')} onClose={() => !busy && setCancelTarget(null)} dismissible={!busy}><div className="ops-form"><Alert variant="warning" title={t('purchaseCancellationImpact')}>{cancelTarget.status === 'VALIDATED' ? t('validatedPurchaseCancellationHint') : t('draftPurchaseCancellationHint')}</Alert><TextInput label={t('reason')} value={cancelReason} minLength={3} required onChange={(event) => setCancelReason(event.target.value)} /><div className="ops-form__actions"><Button variant="secondary" onClick={() => setCancelTarget(null)}>{t('close')}</Button><Button variant="danger" disabled={cancelReason.trim().length < 3 || busy} loading={busy} loadingLabel={t('saving')} onClick={() => { if (actionLock.current) return; actionLock.current = true; setBusy(true); void operationsService.cancelPurchase({ purchaseId: cancelTarget.id, reason: cancelReason, userId }).then(async () => { setCancelTarget(null); setCancelReason(''); await load(); notify(t('purchaseCancelled')); }).catch(() => notify(t('operationFailed'))).finally(() => { actionLock.current = false; setBusy(false); }); }}>{t('confirmCancellation')}</Button></div></div></Modal>}
  </section>;
}
